### ISSUE TITLE
quick-start Sorry，Server Is Error 

### ISSUE THREAD

**Issue by liguobao** [JaredTan95/skywalking-docker#2]
500错误,没有对应日志, agent 连接上去一直timeout

Creating elasticsearch ... done
Creating skywalking    ... done
Attaching to elasticsearch, skywalking
skywalking               | replace {ES_CLUSTER_NAME} to elasticsearch
skywalking               | replace {ES_ADDRESSES} to elasticsearch-service:9300
skywalking               | replace {BIND_HOST} to skywalking
skywalking               | replace {NAMING_BIND_HOST} to skywalking
skywalking               | replace {NAMING_BIND_PORT} to 10800
skywalking               | replace {REMOTE_BIND_PORT} to 11800
skywalking               | replace {AGENT_GRPC_BIND_PORT} to 11800
skywalking               | replace {AGENT_JETTY_BIND_HOST} to skywalking
skywalking               | replace {AGENT_JETTY_BIND_PORT} to 12800
skywalking               | replace {UI_JETTY_BIND_PORT} to 12800
skywalking               | replace {UI_JETTY_BIND_HOST} to 0.0.0.0
skywalking               | SkyWalking Collector started successfully!
skywalking               | SkyWalking Web Application started successfully!
elasticsearch            | [2018-09-17T17:03:14,442][INFO ][o.e.n.Node               ] [elasticsearch_node_1] initializing ...
elasticsearch            | [2018-09-17T17:03:14,695][INFO ][o.e.e.NodeEnvironment    ] [elasticsearch_node_1] using [1] data paths, mounts [[/ (overlay)]], net usable_space [17.8gb], net total_space [62.7gb], spins? [possibly], types [overlay]
elasticsearch            | [2018-09-17T17:03:14,697][INFO ][o.e.e.NodeEnvironment    ] [elasticsearch_node_1] heap size [1.9gb], compressed ordinary object pointers [true]
elasticsearch            | [2018-09-17T17:03:14,707][INFO ][o.e.n.Node               ] [elasticsearch_node_1] node name [elasticsearch_node_1], node ID [O-Mg4HP6Tx2C-Lq7UOVaWw]
elasticsearch            | [2018-09-17T17:03:14,708][INFO ][o.e.n.Node               ] [elasticsearch_node_1] version[5.6.10], pid[1], build[b727a60/2018-06-06T15:48:34.860Z], OS[Linux/4.9.93-linuxkit-aufs/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_171/25.171-b10]
elasticsearch            | [2018-09-17T17:03:14,709][INFO ][o.e.n.Node               ] [elasticsearch_node_1] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.cgroups.hierarchy.override=/, -Xms2g, -Xmx2g, -Des.path.home=/usr/share/elasticsearch]
elasticsearch            | [2018-09-17T17:03:18,263][INFO ][o.e.p.PluginsService     ] [elasticsearch_node_1] loaded module [aggs-matrix-stats]
elasticsearch            | [2018-09-17T17:03:18,263][INFO ][o.e.p.PluginsService     ] [elasticsearch_node_1] loaded module [ingest-common]
elasticsearch            | [2018-09-17T17:03:18,263][INFO ][o.e.p.PluginsService     ] [elasticsearch_node_1] loaded module [lang-expression]
elasticsearch            | [2018-09-17T17:03:18,264][INFO ][o.e.p.PluginsService     ] [elasticsearch_node_1] loaded module [lang-groovy]
elasticsearch            | [2018-09-17T17:03:18,264][INFO ][o.e.p.PluginsService     ] [elasticsearch_node_1] loaded module [lang-mustache]
elasticsearch            | [2018-09-17T17:03:18,264][INFO ][o.e.p.PluginsService     ] [elasticsearch_node_1] loaded module [lang-painless]
elasticsearch            | [2018-09-17T17:03:18,265][INFO ][o.e.p.PluginsService     ] [elasticsearch_node_1] loaded module [parent-join]
elasticsearch            | [2018-09-17T17:03:18,265][INFO ][o.e.p.PluginsService     ] [elasticsearch_node_1] loaded module [percolator]
elasticsearch            | [2018-09-17T17:03:18,266][INFO ][o.e.p.PluginsService     ] [elasticsearch_node_1] loaded module [reindex]
elasticsearch            | [2018-09-17T17:03:18,266][INFO ][o.e.p.PluginsService     ] [elasticsearch_node_1] loaded module [transport-netty3]
elasticsearch            | [2018-09-17T17:03:18,266][INFO ][o.e.p.PluginsService     ] [elasticsearch_node_1] loaded module [transport-netty4]
elasticsearch            | [2018-09-17T17:03:18,268][INFO ][o.e.p.PluginsService     ] [elasticsearch_node_1] loaded plugin [ingest-geoip]
elasticsearch            | [2018-09-17T17:03:18,268][INFO ][o.e.p.PluginsService     ] [elasticsearch_node_1] loaded plugin [ingest-user-agent]
elasticsearch            | [2018-09-17T17:03:18,268][INFO ][o.e.p.PluginsService     ] [elasticsearch_node_1] loaded plugin [x-pack]
elasticsearch            | [2018-09-17T17:03:22,879][INFO ][o.e.x.m.j.p.l.CppLogMessageHandler] [controller/56] [Main.cc@128] controller (64 bit): Version 5.6.10 (Build 68231d1bd2d977) Copyright (c) 2018 Elasticsearch BV
elasticsearch            | [2018-09-17T17:03:23,042][INFO ][o.e.d.DiscoveryModule    ] [elasticsearch_node_1] using discovery type [zen]
elasticsearch            | [2018-09-17T17:03:24,529][INFO ][o.e.n.Node               ] [elasticsearch_node_1] initialized
elasticsearch            | [2018-09-17T17:03:24,530][INFO ][o.e.n.Node               ] [elasticsearch_node_1] starting ...
elasticsearch            | [2018-09-17T17:03:25,075][INFO ][o.e.t.TransportService   ] [elasticsearch_node_1] publish_address {172.23.0.2:9300}, bound_addresses {0.0.0.0:9300}
elasticsearch            | [2018-09-17T17:03:25,098][INFO ][o.e.b.BootstrapChecks    ] [elasticsearch_node_1] bound or publishing to a non-loopback address, enforcing bootstrap checks
elasticsearch            | [2018-09-17T17:03:28,218][INFO ][o.e.c.s.ClusterService   ] [elasticsearch_node_1] new_master {elasticsearch_node_1}{O-Mg4HP6Tx2C-Lq7UOVaWw}{c865getFRH6fXeRq34hD2w}{172.23.0.2}{172.23.0.2:9300}{ml.max_open_jobs=10, ml.enabled=true}, reason: zen-disco-elected-as-master ([0] nodes joined)[, ]
elasticsearch            | [2018-09-17T17:03:28,267][INFO ][o.e.h.n.Netty4HttpServerTransport] [elasticsearch_node_1] publish_address {172.23.0.2:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch            | [2018-09-17T17:03:28,267][INFO ][o.e.n.Node               ] [elasticsearch_node_1] started
elasticsearch            | [2018-09-17T17:03:28,390][INFO ][o.e.g.GatewayService     ] [elasticsearch_node_1] recovered [0] indices into cluster_state
elasticsearch            | [2018-09-17T17:03:28,597][INFO ][o.e.x.m.MachineLearningTemplateRegistry] [elasticsearch_node_1] successfully created .ml-meta index template
elasticsearch            | [2018-09-17T17:03:28,639][INFO ][o.e.x.m.MachineLearningTemplateRegistry] [elasticsearch_node_1] successfully created .ml-state index template
elasticsearch            | [2018-09-17T17:03:28,734][INFO ][o.e.x.m.MachineLearningTemplateRegistry] [elasticsearch_node_1] successfully created .ml-notifications index template
elasticsearch            | [2018-09-17T17:03:29,101][INFO ][o.e.x.m.MachineLearningTemplateRegistry] [elasticsearch_node_1] successfully created .ml-anomalies- index template
elasticsearch            | [2018-09-17T17:03:29,178][INFO ][o.e.l.LicenseService     ] [elasticsearch_node_1] license [31407548-5065-4315-8581-4b0e049a1eab] mode [trial] - valid
elasticsearch            | [2018-09-17T17:03:34,741][INFO ][o.e.c.m.MetaDataCreateIndexService] [elasticsearch_node_1] [.monitoring-es-6-2018.09.17] creating index, cause[auto(bulk api)], templates [.monitoring-es], shards [1]/[1], mappings [doc]
elasticsearch            | [2018-09-17T17:03:34,870][INFO ][o.e.c.m.MetaDataCreateIndexService] [elasticsearch_node_1] [.watches] creating index, cause [auto(bulk api)], templates [watches], shards [1]/[1], mappings [watch]
elasticsearch            | [2018-09-17T17:03:35,092][INFO ][o.e.c.m.MetaDataMappingService] [elasticsearch_node_1] [.watches/06YVX_d7RLiCJ4Xfcso8RA] update_mapping [watch]
elasticsearch            | [2018-09-17T17:04:35,406][INFO ][o.e.c.m.MetaDataCreateIndexService] [elasticsearch_node_1] [.triggered_watches] creating index, cause [auto(bulk api)], templates [triggered_watches], shards [1]/[1], mappings [triggered_watch]
elasticsearch            | [2018-09-17T17:04:35,660][INFO ][o.e.c.m.MetaDataCreateIndexService] [elasticsearch_node_1] [.watcher-history-6-2018.09.17] creating index, cause [auto(bulk api)], templates [.watch-history-6], shards [1]/[1], mappings [doc]
elasticsearch            | [2018-09-17T17:04:35,732][INFO ][o.e.c.m.MetaDataCreateIndexService] [elasticsearch_node_1] [.monitoring-alerts-6] creating index, cause [auto(bulk api)], templates [.monitoring-alerts], shards [1]/[1], mappings [doc]
elasticsearch            | [2018-09-17T17:04:35,805][INFO ][o.e.c.m.MetaDataMappingService] [elasticsearch_node_1] [.watcher-history-6-2018.09.17/L1GCPFtsRG6jme3vR-NVig] update_mapping [doc]
elasticsearch            | [2018-09-17T17:04:35,867][INFO ][o.e.c.m.MetaDataMappingService] [elasticsearch_node_1] [.watcher-history-6-2018.09.17/L1GCPFtsRG6jme3vR-NVig] update_mapping [doc]

API 错误:

{"timestamp":1537175568072,"status":500,"error":"Internal Server Error","exception":"com.netflix.zuul.exception.ZuulException","message":"GENERAL"}

@JaredTan95 

你这边部署没问题么?

**Comment by JaredTan95** [comment]
目前还没有碰到该问题。不过分析下来你可以在运行时设置-e UI_JETTY_BIND_HOST=127.0.0.1试试。同时镜像已经升级至5.0.0-RC2.

**Comment by liguobao** [comment]
我单独启动ES启动,然后单独启动skywalking也是正常的,很奇怪用docker-compose启动是会炸的.

**Comment by liguobao** [comment]
咨询一下,如果我需要在k8s部署skywalking,是否可以使用当前的二合docker 镜像.

**Comment by JaredTan95** [comment]
嗯嗯，是可以的，如果需要集群部署Collector，你可以参考https://github.com/JaredTan95/skywalking-docker/blob/master/5.x/cluster/collector/Dockerfile

**Comment by liguobao** [comment]
我马上去试一下,谢谢了!

**Comment by liguobao** [comment]
我马上去试一下,谢谢了!

**Comment by liguobao** [comment]
@JaredTan95  我看了下集群的配置,如果ES是需要账号密码访问的应该怎么配置呢?

**Comment by JaredTan95** [comment]
Es是6.x的吗？5.x的skywalking用不了带密码的es的。😄

**Comment by liguobao** [comment]
aliyun买的ES5.x 自带密码....
skywalking不是还不支持ES6.x么?
我在官方群看了大家都用ES5.x

**Comment by JaredTan95** [comment]
skywalking 6.x是支持es 6.x的

**Comment by liguobao** [comment]
我咨询一下阿里云 技术支持看看能不能弄, skywalking 6.x release 都还没出来不太敢用.

**Comment by JaredTan95** [comment]
嗯，目前sw6.x 还处于开发阶段

**Comment by liguobao** [comment]
k8s 跑起来了,但是UI访问都是502,看日志都正常,哪里可以看到skywalking的日志么?
启动日志:
replace {ZK_ADDRESSES} to skywalking-collector
replace {ES_CLUSTER_NAME} to es-cn-4590sf27m000rdaz9
replace {ES_ADDRESSES} to es-cn-4590sf27m000rdaz9.elasticsearch.aliyuncs.com:9300
replace {BIND_HOST} to skywalking-collector
replace {NAMING_BIND_HOST} to skywalking-collector
replace {NAMING_BIND_PORT} to 10800
replace {REMOTE_BIND_PORT} to 11800
replace {AGENT_GRPC_BIND_PORT} to 11800
replace {AGENT_JETTY_BIND_HOST} to skywalking-collector
replace {AGENT_JETTY_BIND_PORT} to 12800
replace {UI_JETTY_BIND_PORT} to 8080
replace {UI_JETTY_BIND_HOST} to 0.0.0.0
SkyWalking Collector started successfully!
SkyWalking Web Application started successfully!


➜  ~ kubectl get pod -n dev-ops
NAME                                    READY     STATUS    RESTARTS   AGE
skywalking-collector-68cd7f44cd-2sskf   1/1       Running   0          2m
skywalking-collector-68cd7f44cd-l52ml   1/1       Running   0          2m
skywalking-collector-68cd7f44cd-xhvfd   1/1       Running   0          2m

**Comment by JaredTan95** [comment]
@liguobao 日志挂载 -v /your/log/path:/apache-skywalking-apm-incubating/logs。你可以将你的k8s编排分享？

**Comment by liguobao** [comment]
完整的Yaml文件如下:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    run: skywalking-collector
  name: skywalking-collector
  namespace: dev-ops
spec:
  replicas: 3
  selector:
    matchLabels:
      run: skywalking-collector
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: skywalking-collector
    spec:
      containers:
      - env:
        - name: ES_CLUSTER_NAME
          value: aliyun-es
        - name: ES_ADDRESSES
          value: aliyun-es:9300
        - name: BIND_HOST
          value: skywalking-collector
        - name: AGENT_JETTY_BIND_HOST
          value: skywalking-collector
        - name: NAMING_BIND_HOST
          value: skywalking-collector
        - name: ZK_ADDRESSES
          value: skywalking-collector
        - name: UI_JETTY_BIND_HOST
          value: 0.0.0.0
        - name: UI_JETTY_BIND_PORT
          value: "8080"
        image: wutang/skywalking-collector:5.x-zk
        imagePullPolicy: IfNotPresent
        name: skywalking-collector
        ports:
        - containerPort: 8080
          name: service-8080
          protocol: TCP
        - containerPort: 10800
          name: service-10800
          protocol: TCP
        - containerPort: 11800
          name: service-11800
          protocol: TCP
        - containerPort: 12800
          name: service-12800
          protocol: TCP
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-ui
  namespace: dev-ops
spec:
  selector:
    run: skywalking-collector
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-10800
  namespace: dev-ops
spec:
  selector:
    run: skywalking-collector
  ports:
  - protocol: TCP
    port: 80
    targetPort: 10800
---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-11800
  namespace: dev-ops
spec:
  selector:
    run: skywalking-collector
  ports:
  - protocol: TCP
    port: 80
    targetPort: 11800
---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-12800
  namespace: dev-ops
spec:
  selector:
    run: skywalking-collector
  ports:
  - protocol: TCP
    port: 80
    targetPort: 12800
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: skywalking-ingress
  namespace: dev-ops
spec:
  tls:
    - hosts:
      - skywalking.xxxx.org
      secretName: xxxx-org-tls
  rules:
  - host: skywalking.xxx.org
    http:
      paths:
      - backend:
          serviceName: skywalking-ui
          servicePort: 80
        path: /
```

我这边没有部署Zookeeper.
