### ISSUE TITLE
无法通过webapp.yml指定用户名密码，通过环境变量指定后admin账号依然可以登录。

### ISSUE THREAD

**Issue by siegrainwong** [JaredTan95/skywalking-docker#28]
第一种方式是这样的，把包含我用户名密码的配置文件挂载进去，没有效果。
```yaml
  skywalking-ui:
    volumes:
      - ./skywalking-ui-config/webapp.prod.yml:/apache-skywalking-apm-bin/webapp/webapp.yml:ro
```
第二种，指定环境变量
```yaml
  skywalking-ui:
    environment:
      security.user.myusername.password: mypassword
```
这种方式下我能通过新的用户名密码登录，但admin账号也可以登录。。。
